# 数据源配置 
spring:
  datasource:
    # 数据源名称
    name: test
    # 数据库的JDBC URL
    url: jdbc:mysql://localhost:3306/ry?useUnicode=true&characterEncoding=utf8
    # 用户名
    username: root
    # 密码
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # JDBC驱动
    driverClassName: com.mysql.jdbc.Driver
    # 连接初始值，连接池启动时创建的连接数量的初始化的大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    # 该选项用来验证数据库连接的有效性
    validationQuery: select 'x'
    # 失效连接验证
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true