#http://localhost:8080/druid/index.html
# 数据源配置 
spring:
  datasource:
    druid:
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/ry?useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.jdbc.Driver
      name: ty
      
      initial-size: 3
      min-idle: 3
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictableIdle-time-millis: 30000
      # 该选项用来验证数据库连接的有效性
      validation-query: select 'x'
      # 失效连接验证
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true
      aop-patterns: com.line.road.modular.system.service.impl.*
      